In [1]:
import numpy as np

In [10]:
result = [[0.221527, 0.0821552, -0.288575, -0.494866, 0.784861], [-0.315466, 0.179283, -0.93133, 0.0154059, 0.0269214], [-0.188247, -0.40619, 0.130633, -0.850682, 0.242584], [0.679576, -0.0279575, 0.679177, -0.0158776, -0.275427], [0.282004, -0.80226, -0.392452, 0.322446, 0.137335], [-0.520617, 0.202219, -0.296029, 0.27854, 0.723081], [-0.127754, 0.819571, -0.312373, 0.45834, 0.0657852], [0.315112, 0.597254, -0.537187, -0.493568, -0.0741495], [0.56461, 0.0742483, -0.699408, 0.23616, 0.361604], [-0.0254109, -0.643913, 0.752022, -0.129443, 0.0493619], [0.167269, 0.359641, -0.540894, 0.22703, -0.706094], [-0.379647, -0.440479, -0.500155, 0.370383, -0.517874], [0.0593161, -0.792767, -0.0306862, -0.307653, -0.521927], [-0.881714, 0.413645, -0.163215, -0.00853653, -0.157365], [0.236311, -0.512336, 0.250038, 0.593069, -0.517124], [0.777584, 0.503967, 0.117653, -0.0836594, 0.347185], [-0.231043, 0.239015, 0.902784, 0.181117, -0.188025], [0.567185, 0.373166, 0.102121, 0.685842, -0.241329], [0.0215231, 0.510307, 0.462992, 0.414566, 0.59405], [-0.740711, -0.478228, -0.375036, -0.192618, 0.211873], [0.678623, -0.522003, 0.155447, -0.372896, 0.322128], [0.461993, -0.0263072, 0.0881086, -0.780857, -0.410326], [-0.379647, -0.440479, -0.500155, 0.370383, -0.517874], [-0.724885, -0.379233, 0.339656, -0.0366442, -0.462617], [0.198111, 0.846001, 0.321969, -0.0951136, -0.363762], [0.829122, -0.251276, -0.271627, 0.0469449, -0.416449], [0.273568, -0.384271, -0.70794, -0.525592, 0.00831378], [-0.0488231, -0.0628655, -0.378877, 0.910677, 0.144156], [-0.732459, -0.00254821, 0.474199, -0.211467, 0.440355], [0.315112, 0.597254, -0.537187, -0.493568, -0.0741495], [-0.354257, -0.0210929, -0.44778, -0.526998, -0.629143], [-0.459802, -0.357837, 0.441382, 0.650714, 0.205637], [-0.231043, 0.239015, 0.902784, 0.181117, -0.188025], [-0.404445, 0.305211, 0.434409, -0.669951, -0.32515], [-0.378181, 0.261896, 0.134319, 0.687008, -0.546229], [-0.286797, 0.770034, 0.05778, -0.386268, 0.415033], [0.039446, 0.0467684, 0.313931, -0.0873114, -0.94344], [0.173031, 0.19329, 0.724927, -0.490614, 0.408015], [-0.136497, -0.581638, 0.11419, 0.0237904, 0.793385], [0.518921, -0.320079, 0.371333, 0.564494, 0.4144]]
result = np.array(result).transpose()

In [11]:
dot_products = (result.transpose() @ result)

In [12]:
scales = np.sqrt(dot_products.diagonal())

In [13]:
scaled_dots = ((dot_products / scales).transpose()/scales).transpose()

In [14]:
scaled_results = result / scales

In [18]:
scaled_dots

array([[ 1.        ,  0.22710936,  0.49859912, ...,  0.40803895,
         0.49994973,  0.02739899],
       [ 0.22710936,  1.        , -0.14167483, ..., -0.69165306,
        -0.1458408 , -0.54706814],
       [ 0.49859912, -0.14167483,  1.        , ...,  0.49994943,
         0.44909248, -0.29884251],
       ...,
       [ 0.40803895, -0.69165306,  0.49994943, ...,  1.        ,
         0.25877779,  0.18924372],
       [ 0.49994973, -0.1458408 ,  0.44909248, ...,  0.25877779,
         1.        ,  0.49995027],
       [ 0.02739899, -0.54706814, -0.29884251, ...,  0.18924372,
         0.49995027,  1.        ]], shape=(40, 40))

In [16]:
(scaled_results.transpose() @ scaled_results)[0]

array([ 1.        ,  0.22710936,  0.49859912, -0.25606093,  0.05803493,
        0.41638796, -0.04601063,  0.46140454,  0.49995019, -0.17274582,
       -0.44384636, -0.56750153, -0.30052827, -0.23352629, -0.76125799,
        0.49360066, -0.53094859, -0.40197532,  0.17417674,  0.16646081,
        0.49995011,  0.13912768, -0.56750153, -0.63471057, -0.21795629,
       -0.10867218,  0.49995011, -0.24416715,  0.15095478,  0.46140454,
       -0.18398905, -0.41924896, -0.53094859, -0.11354221, -0.86971457,
        0.49994999, -0.77527514,  0.40803895,  0.49994973,  0.02739899])

In [17]:
scaled_dots[scaled_dots - np.eye(dot_products.shape[0]) > 0.53]

array([1., 1., 1., 1., 1., 1.])

In [295]:
(scaled_dots - np.eye(dot_products.shape[0])).max()

np.float64(0.5000005060922263)

In [296]:
np.argwhere(scaled_dots - np.eye(dot_products.shape[0]) > 0.53)

array([], shape=(0, 2), dtype=int64)

In [214]:
check_row = 1

In [215]:
result[:,check_row]

array([-0.844698 ,  0.0745334, -0.448828 , -0.255003 ])

In [216]:
scaled_dots[check_row]

array([-0.78659225,  1.        , -0.20062702, -0.35917036, -0.25994563,
       -0.06584374,  0.02333156, -0.80657197, -0.13819724,  0.49857136,
        0.55106371,  0.16196259,  0.52575217, -0.29553058, -0.35113507,
        0.54995202,  0.49997373,  0.50413116,  0.49670188, -0.8168923 ,
       -0.76611726,  0.3002369 ,  0.061055  , -0.30334284])

In [217]:
DELTA = 1e-5;
RAMP_IN = 5;

In [218]:
scaled_dots[check_row]

array([-0.78659225,  1.        , -0.20062702, -0.35917036, -0.25994563,
       -0.06584374,  0.02333156, -0.80657197, -0.13819724,  0.49857136,
        0.55106371,  0.16196259,  0.52575217, -0.29553058, -0.35113507,
        0.54995202,  0.49997373,  0.50413116,  0.49670188, -0.8168923 ,
       -0.76611726,  0.3002369 ,  0.061055  , -0.30334284])

In [219]:
delta_values = scaled_dots[check_row].copy()
delta_values[check_row] = 0
delta_values = delta_values - (0.5 - (DELTA * RAMP_IN))
delta_values = delta_values * (delta_values > 0)
delta_values = delta_values / RAMP_IN
delta_values = np.minimum(delta_values, DELTA)

In [220]:
delta_values

array([-0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  1.00000000e-05, -0.00000000e+00,
        1.00000000e-05, -0.00000000e+00, -0.00000000e+00,  1.00000000e-05,
        4.74647856e-06,  1.00000000e-05, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00])

In [178]:
delta_values =( scaled_dots[check_row] - (0.5 - (DELTA * RAMP_IN))) / RAMP_IN

In [202]:
(scaled_results * delta_values).sum(1)

array([-1.43666804e-05,  1.48112498e-06, -7.05066059e-06, -6.99218977e-06])

In [203]:
scaled_results[:,check_row]

array([-0.81824052,  0.08589409, -0.4070275 , -0.39677861])

In [204]:
(scaled_results * delta_values).sum(1) / scaled_results[:,check_row]

array([1.75580163e-05, 1.72436200e-05, 1.73223198e-05, 1.76223960e-05])

In [176]:
scaled_results[:,scaled_dots[check_row] > 0.5]

array([[-0.81824052, -0.42667648],
       [ 0.08589409,  0.35453458],
       [-0.4070275 , -0.05804024],
       [-0.39677861, -0.82999021]])

In [177]:
scaled_results[:,scaled_dots[check_row] > 0.5 - (RAMP_IN * DELTA)]

array([[-0.81824052, -0.42667648, -0.7630905 , -0.49175276, -0.88432235,
        -0.1026002 , -0.43680969],
       [ 0.08589409,  0.35453458,  0.54403284, -0.69610038, -0.2944908 ,
         0.07540344, -0.62293359],
       [-0.4070275 , -0.05804024,  0.33862954, -0.50805769,  0.31793376,
        -0.99174969,  0.1367669 ],
       [-0.39677861, -0.82999021,  0.08397145,  0.12450248,  0.1736873 ,
        -0.014835  , -0.6343862 ]])

In [158]:
scaled_results[:,scaled_dots[check_row] > 0.5].sum(1)

array([-1.24491701,  0.44042867, -0.46506774, -1.22676881])

In [160]:
scaled_results[:,scaled_dots[check_row] > 0.5].sum(1) / scaled_results[:,check_row]

array([1.52145606, 5.12757846, 1.14259536, 3.09182196])

In [19]:
scores_1 = [(12345,1.44587),
(12347,1.22661),
(12348,1.20186),
(12349,1.12461),
(12351,0.996594),
(12350,1.48207),
(12346,1.10058),
(12354,1.40476),
(12352,1.18128),
(12356,1.34566),
(12355,1.22234),
(12357,1.37413),
(12353,1.53294),
(12358,1.04816),
(12361,1.24213),
(12363,1.51516),
(12360,1.00632),
(12364,1.53368),
(12362,1.33391),
(12359,1.52417),
(12365,1.42502),
(12366,1.28773),
(12368,1.36497),
(12370,1.20187),
(12367,1.26827),
(12369,1.64823),
(12372,1.36062),
(12371,1.02878),
(12373,1.0281),
(12375,1.57475),
(12374,1.39244),
(12376,1.80172),
(12378,1.18716),
(12377,1.67795),
(12379,1.60843),
(12380,1.03979),
(12381,1.29866),
(12382,1.10061),
(12383,0.999367),
(12385,1.00614),
(12384,1.03602),
(12386,1.72568),
(12387,0.783802),
(12388,1.58152),
(12391,1.42412),
(12390,1.43683),
(12392,1.44099),
(12393,1.26652),
(12389,0.758159),
(12396,0.981024),
(12395,1.23321),
(12394,1.54171),
(12398,1.06473),
(12400,1.32287),
(12399,1.81113),
(12397,1.73613),
(12401,1.05784),
(12402,2.64413),
(12403,0.97261),
(12404,1.5243),
(12406,1.16642),
(12407,1.20738),
(12405,1.5384),
(12408,1.14269),
(12409,1.34926),
(12410,1.18497),
(12412,1.22802),
(12411,1.48344),
(12414,1.51831),
(12413,1.04832),
(12415,0.750548),
(12416,1.04287),
(12417,1.53292),
(12418,1.44359),
(12421,1.43628),
(12420,1.30557),
(12419,1.25073),
(12422,1.48197),
(12423,1.14976),
(12424,0.732751),
(12425,1.62433),
(12428,1.14663),
(12427,1.52119),
(12426,1.69553),
(12429,1.08158),
(12430,0.958432),
(12431,1.29699),
(12432,1.01636),
(12434,1.54087),
(12433,1.53052),
(12435,1.16289),
(12436,1.5606),
(12437,1.51329),
(12440,0.744972),
(12438,1.25009),
(12439,1.30839),
(12441,0.987512),
(12442,1.30547),
(12443,1.36554),
(12444,1.04257),
(12445,1.26004),
(12447,1.48304),
(12446,1.34538),
(12448,1.66404),
(12449,1.05871),
(12450,0.986897),
(12452,1.31676),
(12451,0.809684),
(12453,1.65707),
(12454,1.18971),
(12455,1.21568),]

In [20]:
sorted(scores_1)

[(12345, 1.44587),
 (12346, 1.10058),
 (12347, 1.22661),
 (12348, 1.20186),
 (12349, 1.12461),
 (12350, 1.48207),
 (12351, 0.996594),
 (12352, 1.18128),
 (12353, 1.53294),
 (12354, 1.40476),
 (12355, 1.22234),
 (12356, 1.34566),
 (12357, 1.37413),
 (12358, 1.04816),
 (12359, 1.52417),
 (12360, 1.00632),
 (12361, 1.24213),
 (12362, 1.33391),
 (12363, 1.51516),
 (12364, 1.53368),
 (12365, 1.42502),
 (12366, 1.28773),
 (12367, 1.26827),
 (12368, 1.36497),
 (12369, 1.64823),
 (12370, 1.20187),
 (12371, 1.02878),
 (12372, 1.36062),
 (12373, 1.0281),
 (12374, 1.39244),
 (12375, 1.57475),
 (12376, 1.80172),
 (12377, 1.67795),
 (12378, 1.18716),
 (12379, 1.60843),
 (12380, 1.03979),
 (12381, 1.29866),
 (12382, 1.10061),
 (12383, 0.999367),
 (12384, 1.03602),
 (12385, 1.00614),
 (12386, 1.72568),
 (12387, 0.783802),
 (12388, 1.58152),
 (12389, 0.758159),
 (12390, 1.43683),
 (12391, 1.42412),
 (12392, 1.44099),
 (12393, 1.26652),
 (12394, 1.54171),
 (12395, 1.23321),
 (12396, 0.981024),
 (12397,

In [23]:
scores_2 = [(12349,1.2781),
(12346,1.33146),
(12347,1.38734),
(12345,1.30867),
(12351,1.1418),
(12348,1.66234),
(12350,1.49851),
(12352,1.34519),
(12355,0.973486),
(12354,1.01565),
(12356,1.77865),
(12353,1.05299),
(12357,1.02838),
(12358,1.70296),
(12359,1.2603),
(12360,1.09486),
(12363,1.235),
(12361,1.60161),
(12362,1.10574),
(12364,1.39301),
(12365,0.733886),
(12367,1.25765),
(12369,1.16089),
(12368,0.997517),
(12366,1.57313),
(12370,1.06714),
(12371,1.38544),
(12372,1.43292),
(12373,1.39768),
(12375,1.45934),
(12374,1.52581),
(12376,1.04513),
(12378,1.18914),
(12377,1.54136),
(12379,0.743344),
(12380,1.06439),
(12382,1.04738),
(12381,1.07172),
(12383,1.56044),
(12385,1.21082),
(12386,1.21461),
(12384,0.734368),
(12388,1.0914),
(12389,1.19667),
(12390,1.25943),
(12387,1.83582),
(12391,1.42676),
(12392,1.04083),
(12393,0.733097),
(12395,1.12051),
(12396,1.56322),
(12398,1.24692),
(12394,0.733116),
(12397,1.032),
(12399,1.60372),
(12400,1.72274),
(12401,1.10936),
(12402,1.17356),
(12404,1.50808),
(12403,1.30658),
(12405,1.58792),
(12406,1.03524),
(12407,1.36299),
(12409,1.09911),
(12408,0.744179),
(12411,1.15396),
(12410,1.6435),
(12412,1.173),
(12413,1.55377),
(12414,1.01511),
(12415,1.35147),
(12416,1.63561),
(12417,1.65539),
(12419,1.29012),
(12418,1.57463),
(12420,1.33158),
(12421,1.53987),
(12422,1.13692),
(12423,1.17639),
(12426,1.05554),
(12424,1.75774),
(12425,1.04025),
(12427,1.74473),
(12428,1.50169),
(12429,1.02609),
(12430,0.748481),
(12431,0.973481),
(12432,1.33402),
(12433,1.04345),
(12434,1.6037),
(12435,0.734282),
(12436,1.01298),
(12437,1.14402),
(12440,1.3353),
(12438,1.01742),
(12439,0.961676),
(12441,1.02918),
(12442,1.36984),
(12443,1.47239),
(12445,1.28476),
(12446,1.03287),
(12444,0.730099),
(12447,1.69115),
(12448,1.03348),
(12449,1.46015),
(12450,1.63735),
(12451,1.16337),
(12452,1.48374),
(12453,0.744158),
(12454,1.20501),
(12455,1.45583),
(12456,1.64457),
(12457,1.05333),
(12459,1.35457),
(12458,1.41808),
(12461,1.07133),
(12460,1.01743),
(12462,1.01266),
(12463,1.36662),
(12464,1.37239),
(12466,1.49764),
(12467,1.36368),
(12468,1.06474),
(12465,1.51648),
(12469,1.40364),
(12470,1.40315),
(12471,1.0157),
(12472,1.17294),
(12473,1.0758),
(12474,0.746497),
(12475,1.34942),
(12476,1.35607),
(12477,1.2035)]

In [27]:
import pandas as pd

In [38]:
(pd.DataFrame(sorted(scores_2)).set_index(0) - pd.DataFrame(sorted(scores_1)).set_index(0)).dropna()[1].mean()

np.float64(-0.04431335135135135)