In [4]:
import numpy as np

In [16]:
result = [[-0.698158, 0.278805, 0.506372, -0.422414], [0.632777, -0.610162, -0.0788182, -0.470195], [0.983873, 0.11112, -0.00337072, -0.14013], [-0.141376, -0.497612, 0.460787, -0.721159], [-0.439272, -0.225974, -0.869292, 0.0175802], [0.493986, 0.714962, -0.295521, -0.396836], [0.583472, -0.146018, 0.65964, -0.450687], [-0.0302605, -0.863236, -0.477452, -0.161096], [-0.475668, -0.840769, 0.257589, -0.0223134], [0.198172, 0.613168, 0.441968, 0.624035], [0.101403, 0.111603, 0.975927, 0.157577], [-0.918215, 0.175559, -0.299546, -0.190621], [-0.576935, 0.719466, 0.26343, 0.283054], [0.716413, -0.079184, 0.4552, 0.52276], [-0.521146, -0.548678, -0.293954, 0.583911], [-0.389572, 0.155474, 0.0866155, 0.903638], [-0.289771, 0.46506, -0.63687, 0.54236], [-0.0326046, 0.830432, 0.391657, -0.394875], [-0.877983, -0.144893, 0.343323, 0.300478], [0.258877, -0.686761, 0.661907, 0.152391], [0.53879, -0.73641, -0.127096, 0.388916], [0.183367, -0.256939, -0.716723, 0.621825], [-0.342916, 0.819461, -0.405078, -0.21635], [0.40396, -0.207949, -0.866066, -0.20858]]

result = np.array(result).transpose()

In [17]:
dot_products = (result.transpose() @ result)

In [18]:
scales = np.sqrt(dot_products.diagonal())

In [19]:
scaled_dots = ((dot_products / scales).transpose()/scales).transpose()

In [20]:
scaled_results = result / scales

In [21]:
scaled_dots

array([[ 1.        , -0.45318823, -0.59843061,  0.49792265, -0.20393218,
        -0.12755931,  0.07633324, -0.39326556,  0.23754151, -0.00720194,
         0.3879386 ,  0.618843  ,  0.6172091 , -0.51256549, -0.18463374,
        -0.02251988, -0.21962563,  0.61941512,  0.61949426, -0.10141012,
        -0.81011416, -0.82525011,  0.35414738, -0.69044772],
       [-0.45318823,  1.        ,  0.62092462,  0.51693144, -0.07983049,
         0.08622288,  0.61822002,  0.62094271,  0.20220221, -0.57698565,
        -0.15494301, -0.57490491, -0.95791552,  0.21996725, -0.24636963,
        -0.77308854, -0.67193841, -0.37253059, -0.63550073,  0.45902263,
         0.61741337,  0.03691666, -0.58333816,  0.54883354],
       [-0.59843061,  0.62092462,  1.        , -0.09488778, -0.45683071,
         0.622069  ,  0.61876626, -0.10151123, -0.5591635 ,  0.17417518,
         0.08679801, -0.8561751 , -0.52823555,  0.62127045, -0.65454213,
        -0.49293089, -0.30727347,  0.11421229, -0.92318411,  0.15480329,
  

In [22]:
(scaled_results.transpose() @ scaled_results)[0]

array([ 1.        , -0.45318823, -0.59843061,  0.49792265, -0.20393218,
       -0.12755931,  0.07633324, -0.39326556,  0.23754151, -0.00720194,
        0.3879386 ,  0.618843  ,  0.6172091 , -0.51256549, -0.18463374,
       -0.02251988, -0.21962563,  0.61941512,  0.61949426, -0.10141012,
       -0.81011416, -0.82525011,  0.35414738, -0.69044772])

In [23]:
scaled_dots[scaled_dots - np.eye(dot_products.shape[0]) > 0.53]

array([0.618843  , 0.6172091 , 0.61941512, 0.61949426, 0.62092462,
       0.61822002, 0.62094271, 0.61741337, 0.54883354, 0.62092462,
       0.622069  , 0.61876626, 0.62127045, 0.61914054, 0.62040922,
       0.62057266, 0.62071439, 0.61870786, 0.58535539, 0.61148659,
       0.61873882, 0.622069  , 0.61857696, 0.62204996, 0.61822002,
       0.61876626, 0.61914054, 0.61561039, 0.61926466, 0.62094271,
       0.62057266, 0.62078208, 0.5356903 , 0.61741858, 0.61438928,
       0.62040922, 0.62078208, 0.62045425, 0.6211789 , 0.62136609,
       0.61818735, 0.61988354, 0.62082263, 0.62031091, 0.61561039,
       0.61818735, 0.59042483, 0.6195914 , 0.618843  , 0.62071439,
       0.62061841, 0.6213125 , 0.6172091 , 0.61988354, 0.61521064,
       0.60768094, 0.57778485, 0.61946506, 0.62127045, 0.62082263,
       0.59042483, 0.62080588, 0.58976187, 0.61870786, 0.5356903 ,
       0.62045425, 0.61990065, 0.61158586, 0.61918954, 0.62031091,
       0.61521064, 0.61990065, 0.62012316, 0.62076838, 0.58535

In [24]:
(scaled_dots - np.eye(dot_products.shape[0])).max()

np.float64(0.6220690037285429)

In [296]:
np.argwhere(scaled_dots - np.eye(dot_products.shape[0]) > 0.53)

array([], shape=(0, 2), dtype=int64)

In [214]:
check_row = 1

In [215]:
result[:,check_row]

array([-0.844698 ,  0.0745334, -0.448828 , -0.255003 ])

In [216]:
scaled_dots[check_row]

array([-0.78659225,  1.        , -0.20062702, -0.35917036, -0.25994563,
       -0.06584374,  0.02333156, -0.80657197, -0.13819724,  0.49857136,
        0.55106371,  0.16196259,  0.52575217, -0.29553058, -0.35113507,
        0.54995202,  0.49997373,  0.50413116,  0.49670188, -0.8168923 ,
       -0.76611726,  0.3002369 ,  0.061055  , -0.30334284])

In [217]:
DELTA = 1e-5;
RAMP_IN = 5;

In [218]:
scaled_dots[check_row]

array([-0.78659225,  1.        , -0.20062702, -0.35917036, -0.25994563,
       -0.06584374,  0.02333156, -0.80657197, -0.13819724,  0.49857136,
        0.55106371,  0.16196259,  0.52575217, -0.29553058, -0.35113507,
        0.54995202,  0.49997373,  0.50413116,  0.49670188, -0.8168923 ,
       -0.76611726,  0.3002369 ,  0.061055  , -0.30334284])

In [219]:
delta_values = scaled_dots[check_row].copy()
delta_values[check_row] = 0
delta_values = delta_values - (0.5 - (DELTA * RAMP_IN))
delta_values = delta_values * (delta_values > 0)
delta_values = delta_values / RAMP_IN
delta_values = np.minimum(delta_values, DELTA)

In [220]:
delta_values

array([-0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  1.00000000e-05, -0.00000000e+00,
        1.00000000e-05, -0.00000000e+00, -0.00000000e+00,  1.00000000e-05,
        4.74647856e-06,  1.00000000e-05, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00])

In [178]:
delta_values =( scaled_dots[check_row] - (0.5 - (DELTA * RAMP_IN))) / RAMP_IN

In [202]:
(scaled_results * delta_values).sum(1)

array([-1.43666804e-05,  1.48112498e-06, -7.05066059e-06, -6.99218977e-06])

In [203]:
scaled_results[:,check_row]

array([-0.81824052,  0.08589409, -0.4070275 , -0.39677861])

In [204]:
(scaled_results * delta_values).sum(1) / scaled_results[:,check_row]

array([1.75580163e-05, 1.72436200e-05, 1.73223198e-05, 1.76223960e-05])

In [176]:
scaled_results[:,scaled_dots[check_row] > 0.5]

array([[-0.81824052, -0.42667648],
       [ 0.08589409,  0.35453458],
       [-0.4070275 , -0.05804024],
       [-0.39677861, -0.82999021]])

In [177]:
scaled_results[:,scaled_dots[check_row] > 0.5 - (RAMP_IN * DELTA)]

array([[-0.81824052, -0.42667648, -0.7630905 , -0.49175276, -0.88432235,
        -0.1026002 , -0.43680969],
       [ 0.08589409,  0.35453458,  0.54403284, -0.69610038, -0.2944908 ,
         0.07540344, -0.62293359],
       [-0.4070275 , -0.05804024,  0.33862954, -0.50805769,  0.31793376,
        -0.99174969,  0.1367669 ],
       [-0.39677861, -0.82999021,  0.08397145,  0.12450248,  0.1736873 ,
        -0.014835  , -0.6343862 ]])

In [158]:
scaled_results[:,scaled_dots[check_row] > 0.5].sum(1)

array([-1.24491701,  0.44042867, -0.46506774, -1.22676881])

In [160]:
scaled_results[:,scaled_dots[check_row] > 0.5].sum(1) / scaled_results[:,check_row]

array([1.52145606, 5.12757846, 1.14259536, 3.09182196])

In [19]:
scores_1 = [(12345,1.44587),
(12347,1.22661),
(12348,1.20186),
(12349,1.12461),
(12351,0.996594),
(12350,1.48207),
(12346,1.10058),
(12354,1.40476),
(12352,1.18128),
(12356,1.34566),
(12355,1.22234),
(12357,1.37413),
(12353,1.53294),
(12358,1.04816),
(12361,1.24213),
(12363,1.51516),
(12360,1.00632),
(12364,1.53368),
(12362,1.33391),
(12359,1.52417),
(12365,1.42502),
(12366,1.28773),
(12368,1.36497),
(12370,1.20187),
(12367,1.26827),
(12369,1.64823),
(12372,1.36062),
(12371,1.02878),
(12373,1.0281),
(12375,1.57475),
(12374,1.39244),
(12376,1.80172),
(12378,1.18716),
(12377,1.67795),
(12379,1.60843),
(12380,1.03979),
(12381,1.29866),
(12382,1.10061),
(12383,0.999367),
(12385,1.00614),
(12384,1.03602),
(12386,1.72568),
(12387,0.783802),
(12388,1.58152),
(12391,1.42412),
(12390,1.43683),
(12392,1.44099),
(12393,1.26652),
(12389,0.758159),
(12396,0.981024),
(12395,1.23321),
(12394,1.54171),
(12398,1.06473),
(12400,1.32287),
(12399,1.81113),
(12397,1.73613),
(12401,1.05784),
(12402,2.64413),
(12403,0.97261),
(12404,1.5243),
(12406,1.16642),
(12407,1.20738),
(12405,1.5384),
(12408,1.14269),
(12409,1.34926),
(12410,1.18497),
(12412,1.22802),
(12411,1.48344),
(12414,1.51831),
(12413,1.04832),
(12415,0.750548),
(12416,1.04287),
(12417,1.53292),
(12418,1.44359),
(12421,1.43628),
(12420,1.30557),
(12419,1.25073),
(12422,1.48197),
(12423,1.14976),
(12424,0.732751),
(12425,1.62433),
(12428,1.14663),
(12427,1.52119),
(12426,1.69553),
(12429,1.08158),
(12430,0.958432),
(12431,1.29699),
(12432,1.01636),
(12434,1.54087),
(12433,1.53052),
(12435,1.16289),
(12436,1.5606),
(12437,1.51329),
(12440,0.744972),
(12438,1.25009),
(12439,1.30839),
(12441,0.987512),
(12442,1.30547),
(12443,1.36554),
(12444,1.04257),
(12445,1.26004),
(12447,1.48304),
(12446,1.34538),
(12448,1.66404),
(12449,1.05871),
(12450,0.986897),
(12452,1.31676),
(12451,0.809684),
(12453,1.65707),
(12454,1.18971),
(12455,1.21568),]

In [20]:
sorted(scores_1)

[(12345, 1.44587),
 (12346, 1.10058),
 (12347, 1.22661),
 (12348, 1.20186),
 (12349, 1.12461),
 (12350, 1.48207),
 (12351, 0.996594),
 (12352, 1.18128),
 (12353, 1.53294),
 (12354, 1.40476),
 (12355, 1.22234),
 (12356, 1.34566),
 (12357, 1.37413),
 (12358, 1.04816),
 (12359, 1.52417),
 (12360, 1.00632),
 (12361, 1.24213),
 (12362, 1.33391),
 (12363, 1.51516),
 (12364, 1.53368),
 (12365, 1.42502),
 (12366, 1.28773),
 (12367, 1.26827),
 (12368, 1.36497),
 (12369, 1.64823),
 (12370, 1.20187),
 (12371, 1.02878),
 (12372, 1.36062),
 (12373, 1.0281),
 (12374, 1.39244),
 (12375, 1.57475),
 (12376, 1.80172),
 (12377, 1.67795),
 (12378, 1.18716),
 (12379, 1.60843),
 (12380, 1.03979),
 (12381, 1.29866),
 (12382, 1.10061),
 (12383, 0.999367),
 (12384, 1.03602),
 (12385, 1.00614),
 (12386, 1.72568),
 (12387, 0.783802),
 (12388, 1.58152),
 (12389, 0.758159),
 (12390, 1.43683),
 (12391, 1.42412),
 (12392, 1.44099),
 (12393, 1.26652),
 (12394, 1.54171),
 (12395, 1.23321),
 (12396, 0.981024),
 (12397,

In [23]:
scores_2 = [(12349,1.2781),
(12346,1.33146),
(12347,1.38734),
(12345,1.30867),
(12351,1.1418),
(12348,1.66234),
(12350,1.49851),
(12352,1.34519),
(12355,0.973486),
(12354,1.01565),
(12356,1.77865),
(12353,1.05299),
(12357,1.02838),
(12358,1.70296),
(12359,1.2603),
(12360,1.09486),
(12363,1.235),
(12361,1.60161),
(12362,1.10574),
(12364,1.39301),
(12365,0.733886),
(12367,1.25765),
(12369,1.16089),
(12368,0.997517),
(12366,1.57313),
(12370,1.06714),
(12371,1.38544),
(12372,1.43292),
(12373,1.39768),
(12375,1.45934),
(12374,1.52581),
(12376,1.04513),
(12378,1.18914),
(12377,1.54136),
(12379,0.743344),
(12380,1.06439),
(12382,1.04738),
(12381,1.07172),
(12383,1.56044),
(12385,1.21082),
(12386,1.21461),
(12384,0.734368),
(12388,1.0914),
(12389,1.19667),
(12390,1.25943),
(12387,1.83582),
(12391,1.42676),
(12392,1.04083),
(12393,0.733097),
(12395,1.12051),
(12396,1.56322),
(12398,1.24692),
(12394,0.733116),
(12397,1.032),
(12399,1.60372),
(12400,1.72274),
(12401,1.10936),
(12402,1.17356),
(12404,1.50808),
(12403,1.30658),
(12405,1.58792),
(12406,1.03524),
(12407,1.36299),
(12409,1.09911),
(12408,0.744179),
(12411,1.15396),
(12410,1.6435),
(12412,1.173),
(12413,1.55377),
(12414,1.01511),
(12415,1.35147),
(12416,1.63561),
(12417,1.65539),
(12419,1.29012),
(12418,1.57463),
(12420,1.33158),
(12421,1.53987),
(12422,1.13692),
(12423,1.17639),
(12426,1.05554),
(12424,1.75774),
(12425,1.04025),
(12427,1.74473),
(12428,1.50169),
(12429,1.02609),
(12430,0.748481),
(12431,0.973481),
(12432,1.33402),
(12433,1.04345),
(12434,1.6037),
(12435,0.734282),
(12436,1.01298),
(12437,1.14402),
(12440,1.3353),
(12438,1.01742),
(12439,0.961676),
(12441,1.02918),
(12442,1.36984),
(12443,1.47239),
(12445,1.28476),
(12446,1.03287),
(12444,0.730099),
(12447,1.69115),
(12448,1.03348),
(12449,1.46015),
(12450,1.63735),
(12451,1.16337),
(12452,1.48374),
(12453,0.744158),
(12454,1.20501),
(12455,1.45583),
(12456,1.64457),
(12457,1.05333),
(12459,1.35457),
(12458,1.41808),
(12461,1.07133),
(12460,1.01743),
(12462,1.01266),
(12463,1.36662),
(12464,1.37239),
(12466,1.49764),
(12467,1.36368),
(12468,1.06474),
(12465,1.51648),
(12469,1.40364),
(12470,1.40315),
(12471,1.0157),
(12472,1.17294),
(12473,1.0758),
(12474,0.746497),
(12475,1.34942),
(12476,1.35607),
(12477,1.2035)]

In [27]:
import pandas as pd

In [38]:
(pd.DataFrame(sorted(scores_2)).set_index(0) - pd.DataFrame(sorted(scores_1)).set_index(0)).dropna()[1].mean()

np.float64(-0.04431335135135135)