In [5]:
import numpy as np

In [6]:
result = (cos_theta - 0.5)

In [285]:
result = [[-0.733296, -0.668161, 0.0518386, 0.023282], [-0.669978, 0.730041, -0.0391551, -0.0634644], [0.669978, -0.730041, 0.0391551, 0.0634644], [0.733296, 0.668161, -0.0518386, -0.023282], [-0.709488, -0.0154582, -0.694472, -0.0385566], [-0.693785, 0.0773386, 0.707156, -0.00162585], [0.693785, -0.0773386, -0.707156, 0.00162585], [0.709488, 0.0154582, 0.694472, 0.0385566], [-0.683273, -0.0119945, 0.0274426, -0.720855], [-0.72, 0.0738749, -0.0147591, 0.680672], [0.72, -0.0738749, 0.0147591, -0.680672], [0.683273, 0.0119945, -0.0274426, 0.720855], [-0.0395107, -0.745499, -0.655317, 0.0249078], [-0.0238075, -0.652702, 0.746311, 0.0618386], [0.0238075, 0.652702, -0.746311, -0.0618386], [0.0395107, 0.745499, 0.655317, -0.0249078], [-0.0132955, -0.742036, 0.0665977, -0.65739], [-0.0500228, -0.656166, 0.024396, 0.744137], [0.0500228, 0.656166, -0.024396, -0.744137], [0.0132955, 0.742036, -0.0665977, 0.65739], [0.010512, -0.0893331, -0.679713, -0.719229], [-0.0262153, -0.00346369, -0.721915, 0.682298], [0.0262153, 0.00346369, 0.721915, -0.682298], [-0.010512, 0.0893331, 0.679713, 0.719229]]
result = np.array(result).transpose()

In [286]:
prev = [[0.546266, -0.27887, 0.780403, -0.0667982], [-0.814816, 0.0855346, -0.405324, -0.395118], [-0.0280642, 0.686867, 0.128158, 0.709521], [0.202877, -0.962073, 0.153983, 0.0530379], [0.419062, -0.496464, -0.59073, 0.471958], [0.679969, 0.620985, 0.380867, -0.00193258], [-0.201741, -0.496325, 0.0996721, 0.833312], [0.640997, -0.0433501, 0.23244, 0.724315], [0.438195, 0.392822, -0.507918, -0.621478], [-0.659259, 0.168892, -0.43048, 0.588195], [-0.425092, 0.353218, -0.0578247, -0.826908], [0.261621, -0.580446, -0.566141, -0.518096], [-0.759326, 0.541349, 0.336959, 0.0835572], [0.594634, 0.476308, -0.532992, 0.358148], [0.391671, -0.131411, 0.238721, -0.873977], [-0.489855, -0.693414, -0.506097, 0.124022], [-0.880212, -0.293122, 0.316456, 0.17288], [-0.102105, 0.0750395, -0.986963, -0.0147634], [-0.219857, 0.876088, -0.411559, -0.0832291], [0.679969, 0.620985, 0.380867, -0.00193258], [0.961621, -0.183372, -0.116012, -0.140363], [-0.435261, -0.620725, 0.136282, -0.632137], [-0.0785639, 0.396981, 0.793478, -0.445445], [-0.181677, 0.0570113, 0.849981, 0.483424]]
prev = np.array(prev).transpose()

In [287]:
(result - prev).sum()

np.float64(-0.8099798399999987)

In [288]:
dot_products = (result.transpose() @ result)

In [289]:
scales = np.sqrt(dot_products.diagonal())

In [290]:
scaled_dots = ((dot_products / scales).transpose()/scales).transpose()

In [291]:
scaled_results = result / scales

In [292]:
scaled_dots[0]

array([ 1.00000000e+00, -6.16175754e-08,  6.16175754e-08, -1.00000000e+00,
        4.99999748e-01,  4.99999604e-01, -4.99999604e-01, -4.99999748e-01,
        4.99999669e-01,  4.99999820e-01, -4.99999820e-01, -4.99999669e-01,
        5.00000069e-01,  4.99999843e-01, -4.99999843e-01, -5.00000069e-01,
        5.00000411e-01,  5.00000058e-01, -5.00000058e-01, -5.00000411e-01,
        2.63090244e-08,  7.72944766e-08, -7.72944766e-08, -2.63090244e-08])

In [293]:
(scaled_results.transpose() @ scaled_results)[0]

array([ 1.00000000e+00, -6.16175754e-08,  6.16175754e-08, -1.00000000e+00,
        4.99999748e-01,  4.99999604e-01, -4.99999604e-01, -4.99999748e-01,
        4.99999669e-01,  4.99999820e-01, -4.99999820e-01, -4.99999669e-01,
        5.00000069e-01,  4.99999843e-01, -4.99999843e-01, -5.00000069e-01,
        5.00000411e-01,  5.00000058e-01, -5.00000058e-01, -5.00000411e-01,
        2.63090244e-08,  7.72944766e-08, -7.72944766e-08, -2.63090244e-08])

In [294]:
scaled_dots[scaled_dots - np.eye(dot_products.shape[0]) > 0.53]

array([], dtype=float64)

In [295]:
(scaled_dots - np.eye(dot_products.shape[0])).max()

np.float64(0.5000005060922263)

In [296]:
np.argwhere(scaled_dots - np.eye(dot_products.shape[0]) > 0.53)

array([], shape=(0, 2), dtype=int64)

In [214]:
check_row = 1

In [215]:
result[:,check_row]

array([-0.844698 ,  0.0745334, -0.448828 , -0.255003 ])

In [216]:
scaled_dots[check_row]

array([-0.78659225,  1.        , -0.20062702, -0.35917036, -0.25994563,
       -0.06584374,  0.02333156, -0.80657197, -0.13819724,  0.49857136,
        0.55106371,  0.16196259,  0.52575217, -0.29553058, -0.35113507,
        0.54995202,  0.49997373,  0.50413116,  0.49670188, -0.8168923 ,
       -0.76611726,  0.3002369 ,  0.061055  , -0.30334284])

In [217]:
DELTA = 1e-5;
RAMP_IN = 5;

In [218]:
scaled_dots[check_row]

array([-0.78659225,  1.        , -0.20062702, -0.35917036, -0.25994563,
       -0.06584374,  0.02333156, -0.80657197, -0.13819724,  0.49857136,
        0.55106371,  0.16196259,  0.52575217, -0.29553058, -0.35113507,
        0.54995202,  0.49997373,  0.50413116,  0.49670188, -0.8168923 ,
       -0.76611726,  0.3002369 ,  0.061055  , -0.30334284])

In [219]:
delta_values = scaled_dots[check_row].copy()
delta_values[check_row] = 0
delta_values = delta_values - (0.5 - (DELTA * RAMP_IN))
delta_values = delta_values * (delta_values > 0)
delta_values = delta_values / RAMP_IN
delta_values = np.minimum(delta_values, DELTA)

In [220]:
delta_values

array([-0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  1.00000000e-05, -0.00000000e+00,
        1.00000000e-05, -0.00000000e+00, -0.00000000e+00,  1.00000000e-05,
        4.74647856e-06,  1.00000000e-05, -0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -0.00000000e+00, -0.00000000e+00])

In [178]:
delta_values =( scaled_dots[check_row] - (0.5 - (DELTA * RAMP_IN))) / RAMP_IN

In [202]:
(scaled_results * delta_values).sum(1)

array([-1.43666804e-05,  1.48112498e-06, -7.05066059e-06, -6.99218977e-06])

In [203]:
scaled_results[:,check_row]

array([-0.81824052,  0.08589409, -0.4070275 , -0.39677861])

In [204]:
(scaled_results * delta_values).sum(1) / scaled_results[:,check_row]

array([1.75580163e-05, 1.72436200e-05, 1.73223198e-05, 1.76223960e-05])

In [176]:
scaled_results[:,scaled_dots[check_row] > 0.5]

array([[-0.81824052, -0.42667648],
       [ 0.08589409,  0.35453458],
       [-0.4070275 , -0.05804024],
       [-0.39677861, -0.82999021]])

In [177]:
scaled_results[:,scaled_dots[check_row] > 0.5 - (RAMP_IN * DELTA)]

array([[-0.81824052, -0.42667648, -0.7630905 , -0.49175276, -0.88432235,
        -0.1026002 , -0.43680969],
       [ 0.08589409,  0.35453458,  0.54403284, -0.69610038, -0.2944908 ,
         0.07540344, -0.62293359],
       [-0.4070275 , -0.05804024,  0.33862954, -0.50805769,  0.31793376,
        -0.99174969,  0.1367669 ],
       [-0.39677861, -0.82999021,  0.08397145,  0.12450248,  0.1736873 ,
        -0.014835  , -0.6343862 ]])

In [158]:
scaled_results[:,scaled_dots[check_row] > 0.5].sum(1)

array([-1.24491701,  0.44042867, -0.46506774, -1.22676881])

In [160]:
scaled_results[:,scaled_dots[check_row] > 0.5].sum(1) / scaled_results[:,check_row]

array([1.52145606, 5.12757846, 1.14259536, 3.09182196])